#sensors:
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: /cam3d_throttled/depth_registered/points
#    max_range: 3.0
#    padding_offset: 0.04
#    padding_scale: 1
#    point_subsample: 1

sensors:
 - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
   image_topic: /cam3d/depth_registered/image_raw
   queue_size: 5
   near_clipping_plane_distance: 0.3
   far_clipping_plane_distance: 2.0
   skip_vertical_pixels: 1
   skip_horizontal_pixels: 1
   shadow_threshold: 0.2
   padding_scale: 5.0
   padding_offset: 0.03
   filtered_cloud_topic: output_cloud
